# NLogistic Enterprise Email Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.username=mohitgup1011@gmail.com
mail.smtp.password=
mail.from.email=mohitgup1011@gmail.com
mail.from.name=NLogistic Enterprise Support
