package com.nlogistic.controller;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.nlogistic.model.User;
import com.nlogistic.util.DBConnectionManager;

@WebServlet("/barcodes")
public class BarcodeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        User user = (User) request.getSession().getAttribute("user");
        if (user == null || user.getRoleId() > 3) {
            response.sendError(HttpServletResponse.SC_FORBIDDEN, "Access Denied");
            return;
        }

        List<Map<String, Object>> barcodeList = new ArrayList<>();
        
        // Fetch recent barcodes generated by this company's staff
        String sql = "SELECT b.barcode_id, b.barcode_value, b.barcode_type, b.entity_type, b.entity_id, b.generated_at, u.username "
                   + "FROM barcode_entries b "
                   + "JOIN users u ON b.generated_by = u.user_id "
                   + "ORDER BY b.generated_at DESC LIMIT 50";

        try (Connection conn = DBConnectionManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
             
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Map<String, Object> row = new HashMap<>();
                    row.put("barcodeId", rs.getInt("barcode_id"));
                    row.put("barcodeValue", rs.getString("barcode_value"));
                    row.put("barcodeType", rs.getString("barcode_type"));
                    row.put("entityType", rs.getString("entity_type"));
                    row.put("entityId", rs.getInt("entity_id"));
                    row.put("generatedAt", rs.getTimestamp("generated_at"));
                    row.put("username", rs.getString("username"));
                    barcodeList.add(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        request.setAttribute("barcodeList", barcodeList);
        request.getRequestDispatcher("/jsp/barcode-management.jsp").forward(request, response);
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        User user = (User) request.getSession().getAttribute("user");
        if (user == null || user.getRoleId() > 3) {
            response.sendError(HttpServletResponse.SC_FORBIDDEN, "Access Denied");
            return;
        }

        String entityType = request.getParameter("entityType"); // Container, Shipment, Stock
        int entityId = Integer.parseInt(request.getParameter("entityId"));
        String barcodeType = request.getParameter("barcodeType"); // Code128, QR
        
        // Generate a unique barcode value e.g., SHP-101-ABCD
        String prefix = entityType.substring(0, 3).toUpperCase();
        String uniqueHash = Long.toHexString(System.currentTimeMillis()).toUpperCase().substring(5);
        String barcodeValue = prefix + "-" + entityId + "-" + uniqueHash;

        String sql = "INSERT INTO barcode_entries (barcode_value, barcode_type, entity_type, entity_id, generated_by, image_path) "
                   + "VALUES (?, ?, ?, ?, ?, 'CLIENT_RENDERED')";
                   
        try (Connection conn = DBConnectionManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
             
            ps.setString(1, barcodeValue);
            ps.setString(2, barcodeType);
            ps.setString(3, entityType);
            ps.setInt(4, entityId);
            ps.setInt(5, user.getUserId());
            
            ps.executeUpdate();
            request.getSession().setAttribute("successMessage", "Barcode/QR Code successfully generated for " + entityType + " #" + entityId);
            
        } catch (Exception e) {
            e.printStackTrace();
            request.getSession().setAttribute("errorMessage", "Failed to generate barcode: " + e.getMessage());
        }
        
        response.sendRedirect(request.getContextPath() + "/barcodes");
    }
}
